export const BOOKS_LOADED = 'FETCH_BOOKS_SUCCESS';
export const BOOKS_REQUESTED = 'FETCH_BOOKS_REQUEST';
export const BOOKS_FAILED = 'FETCH_BOOKS_FAILURE';

export const BASKET_LOADED = 'FETCH_BASKET_SUCCESS';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';